# Site Settings
title: Jerry Wiltse - Resume
url: 'https://solvingj.github.io/online-cv/'
baseurl: '/online-cv' 

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Jerry Wiltse
tagline: "Polyglot Developer :: Problem Solver"
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "I am a software developer with an extensive background in enterprise and cloud-based technology.  I'm very active on github, as well as several developer communities (online and local).  I constantly seek out and engage other developers from whom I can learn new skills, techniques, and ways of thinking. My strengths include my commitment to constant self-improvement, and a talent for finding the most efficient solutions to problems."

#sidebar links
email: jerrywiltse@gmail.com
phone: 248 893 9110
website: solvingj.github.io #do not add http://
linkedin: geraldwiltse
github: solvingj
twitter: '@solvingj'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
